run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      prevent_unmaintained_packages:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com
        deny:
          - pkg: reflect
            desc: "Please don't use reflect package"
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  varnamelen:
    max-distance: 5
    min-name-length: 3
    ignore-names:
      - err
    ignore-decls:
      - bc BotController
      - wg sync.WaitGroup
      - wg *sync.WaitGroup
      - db *gorm.DB
      - tx *gorm.DB
      - b *bot.Bot
  tagliatelle:
    case:
      use-field-name: false
      rules:
        json: snake
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - .Do(

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustruct
    - exhaustivestruct
    - nonamedreturns
    - nlreturn
