# https://github.com/actions/go-dependency-submission
name: dependency-submission
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - uses: actions/go-dependency-submission@v2
        with:
          go-mod-path: go.mod